### ISSUE TITLE
auction winners calculation wrong

### ISSUE THREAD

**Issue by mcherifldn** [olegabu/synswap-issues#10]
we submitted MemberId-e bid 1,000,000 for 90% of portfolio
and
MemberId-f bid 2,000,000 for 80% of portfolio

F has a higher bid (comparing 1,000,000/.9 and 2,000,000/.8)

so we should have 80% of portfolio for F with a cash of 2,000,000
and 20% for E with a cash of 222,222

see below wrong result of web app:

MemberId-e@e.com
submitted
2016-07-20
share
0.9
value
USD 1000000
MemberId-f@f.com
submitted
2016-07-20
share
0.09999999999999998
value
USD 199999.99999999994

**Comment by olegabu** [comment]
please verify
initial bids:
[Bid{memberId=MemberId~e@e.com, date=2016-11-21, share=0.9, value=USD 1000000}, Bid{memberId=MemberId~f@f.com, date=2016-11-21, share=0.8, value=USD 2000000}]

winners:
[Bid{memberId=MemberId~e@e.com, date=2016-11-21, share=0.9, value=USD 1000000}, Bid{memberId=MemberId~f@f.com, date=2016-11-21, share=0.1, value=USD 250000}]
