### ISSUE TITLE
prevent addTrade while market is closed

### ISSUE THREAD

**Issue by olegabu** [olegabu/synswap-issues#16]
either disallow trading after close 16:00 or have settle() pick up all trades not yet settled regardless of date

**Comment by olegabu** [comment]
prevent addTrade while market is closed (1600 to 0800)
prevent match and other methods that may interfere while clearing workflows are running (1600 to 2000)

return well worded exception explaining why this method is not allowed at the time

**Comment by choojoyq** [comment]
won't fix

**Comment by olegabu** [comment]
not possible in the current design where chaincodes don't know time
