### ISSUE TITLE
multilateral netting ignores satisfied bilateral payments

### ISSUE THREAD

**Issue by olegabu** [olegabu/synswap-issues#37]
when organizer gathers payment requests to include in its multilateral netting, relationships should return unsatisfied payment requests or partially satisfied with unstatisfiedAmount

here's the scenario Mohammed was testing:

3 trades, 3 VM payments:

A receive 15 from B
A pay 5 to C

B receive 70 from C
B pay 15 to A

C receive 5 from A
C pay 70 to B

So to sum up:
A receive 10
B receive 55
C pay 65

BUT:
I made a bilateral payment before running the multilateral netting:
A pay 5 to C

This payment is not taken into account in the multilateral payment.

**Comment by olegabu** [comment]
![screenshot from 2017-03-08 20-21-35](https://cloud.githubusercontent.com/assets/87353/23730303/3dcd8f24-0413-11e7-9574-e7404df92c6f.png)

**Comment by choojoyq** [comment]
fixed
