### ISSUE TITLE
Payment box not necessary after default

### ISSUE THREAD

**Issue by mcherifldn** [olegabu/synswap-issues#38]
After a payment is missed, GUI should not offer me to pay the missing cash flow, as it is not possible anymore.

![screen shot 2017-03-10 at 10 50 29](https://cloud.githubusercontent.com/assets/23439248/23792597/7ecd31d8-057f-11e7-8c03-ea52fb288549.png)

**Comment by olegabu** [comment]
fixed in Tom's GUI on master
