### ISSUE TITLE
multilateral trade compression unwinds and novates the same trade

### ISSUE THREAD

**Issue by olegabu** [olegabu/synswap-issues#40]
can replicate consistently now:
3 traders a-b-c
a buys from b COMP01
a buys from c COMP02
b buys from c COMP02
once settled, the multi compression workflow will 
unwind a buys from c COMP02 and novate a buys from c COMP02
unwind a buys from c COMP02 and novate a buys from c COMP02

please see if it is a flaw in compression logic which can be corrected, or add a check not to unwind and create identical trades

![screenshot from 2017-03-21 13-33-53](https://cloud.githubusercontent.com/assets/87353/24162070/2b614760-0e1b-11e7-9140-5299f22db1f5.png)
![screenshot from 2017-03-21 13-35-05](https://cloud.githubusercontent.com/assets/87353/24162072/2d44c552-0e1b-11e7-86c4-081a23cf3049.png)

**Comment by choojoyq** [comment]
During multilateral compression implementation we decided that it's fine to unwind all trades which come into compression and send instructions with new trades to all parties. This particular case is in coherence with behavior given higher. So if you've decided that such logic isn't true anymore its obviously new requirement, but not a bug.

**Comment by olegabu** [comment]
it may be acceptable to erase all _payments_ and replace them with new ones but certainly wrong for trades. You cannot unwind all trades and create new ones. Unwinding a trade involves returning money and should not be done unless needed. Trade compression unwinds only the trades that need to be unwound. The current behavior is wrong, very evident and needs to be fixed asap. That's my last comment on that. Turning back to a bug. Please fix this.

**Comment by choojoyq** [comment]
Implemented
