### ISSUE TITLE
Matching a trade after trade date

### ISSUE THREAD

**Issue by mcherifldn** [olegabu/synswap-issues#41]
Matching a trade after trade date does not generate flows.
Generation of flows need to be done on the matching date, with UF payment and IM payment at matching date and not trade date to avoid a default.

**Comment by olegabu** [comment]
if you haven't matched by the close of settlement date (you can set one explicitly) the trade will not settle and won't generate flows, regardless of whether it's matched or not.
you can create another issue for Tom to not show match button for trades who passed settlement date but are not settled, but I think it's a rare use case, low priority
