### ISSUE TITLE
IM amount is a sum of absolute values of IM shares regardless of trade direction

### ISSUE THREAD

**Issue by olegabu** [olegabu/synswap-issues#45]
when netting IM amounts don't take direction of the trade into account, unlike for VM and cash. The sum of the absolute values of IM amounts is the netted amount. The only amount that can offset (subtract from) IM is the return IM amount.
![screenshot from 2017-03-23 13-41-07](https://cloud.githubusercontent.com/assets/87353/24299165/1f1560d8-105d-11e7-928e-0393d7fe02e9.png)
for these trades the IM payments netted bilaterally are
a-b 60000
b-a 60000
not 40000

these actions:

new trade: a sell b 10000
new trade: a buy b 20000
unwind trade: a sell b 10000

generate these IM payment requests:

a-b 10000
b-a 10000
a-b 20000
b-a 20000

and return IM requests:

a-b 10000
b-a 10000

will net to:

a-b: 10000 + 20000 - 10000 = 20000
b-a: 10000 + 20000 - 10000 = 20000

**Comment by mcherifldn** [comment]
I agree with Oleg's calculations.

**Comment by choojoyq** [comment]
Sorry, but i can't fix/implement any bugs/features until i get feedback for my emails which were sent to your "@synswap.com" email domain 5 days ago, please take a look

**Comment by olegabu** [comment]
please see screenshots. The 3 trades:
![screenshot from 2017-04-04 15-30-02](https://cloud.githubusercontent.com/assets/87353/24675204/bd6d6868-192a-11e7-8335-b7db5416f64d.png)

should produce IM payments of
a-b 60000
b-a 60000

not:
![screenshot from 2017-04-04 15-30-51](https://cloud.githubusercontent.com/assets/87353/24675200/bb19753e-192a-11e7-91af-27400ebef8a4.png)

a-b 40000
b-a 40000

**Comment by choojoyq** [comment]
Unable to reproduce through unit and UI tests.
For such 3 trades i get a single IM payment with amount 60000.
Note that you have millions in trades and tens of thousands in payments.

<img width="262" alt="2017-04-05 1 20 33" src="https://cloud.githubusercontent.com/assets/13151161/24681523/443733b0-199e-11e7-8bc4-8c56ca976c30.png">
<img width="388" alt="2017-04-05 1 20 19" src="https://cloud.githubusercontent.com/assets/13151161/24681524/4439d412-199e-11e7-8d9a-9ef61306edda.png">

**Comment by olegabu** [comment]
confirm, no issue. Previous tests must have been affected by return payment requests.
