### ISSUE TITLE
Different timing when updating the status of paid payments

### ISSUE THREAD

**Issue by sophiagrami** [olegabu/synswap-issues#50]
When a payment is paid, the status changes to "paid" in the netted tables but not in the tables under it (the line remains in orange). It is then updated when we click to move forward by 4h.
![screen shot 2017-04-03 at 16 43 06](https://cloud.githubusercontent.com/assets/24411896/24617828/f4302064-188c-11e7-8d98-57c885718d1c.png)

**Comment by olegabu** [comment]
bilateral payment requests are not satisfied until the netting workflow is closed. The fact that one of the netted requests is satisfied (green) does not yet mean that others have paid their part and the netting is complete. Only after the netting round is closed, the fact that everyone paid their part is verified, and all relationships are notified their bilateral requests are satisfied by netted payments. Only then bilateral requests turn green.
