### ISSUE TITLE
Trade matched but no flows issued

### ISSUE THREAD

**Issue by mcherifldn** [olegabu/synswap-issues#51]
If a trade is matched a 2100 then the status is matched but the deal will not generate any flows.
It's a limit situation, but we should not be able to match after the close so the flows are correctly calculated.
![screen shot 2017-04-04 at 00 01 01](https://cloud.githubusercontent.com/assets/23439248/24635228/0c775394-18ca-11e7-92dc-e8b4077547e0.png)

**Comment by olegabu** [comment]
don't allow to match if passed settlement date
