### ISSUE TITLE
"pay buyer VM" and "pay seller VM" inverted

### ISSUE THREAD

**Issue by mcherifldn** [olegabu/synswap-issues#9]
"pay buyer VM" button should be in the seller page and not the buyer page. and vice versa.

**Comment by olegabu** [comment]
pay buyer IM as well as pay buyer VM means 'the network requests the buyer to pay into IM or VM account'
how should I rephrase it?

**Comment by mcherifldn** [comment]
"pay buyer VM" = "the network requests the seller to pay into the buyer VM account"
"requests to pay into buyer VM" is correct and shows the correct cash flow paid or to be paid.

let's take an exemple:
A buyer / B seller
new trade with UF = 500
Buyer A pays 500 UF to Seller B
the day after price goes to 550
then Seller B pays to Buyer A 50 into VM account
so we should have in the page of Seller B the amount 50 pre-filed next to the button "pay buyer VM"

**Comment by olegabu** [comment]
take a look at chaincode trade a buys from b b13d85007e94ffedde644d60b0b9b85f2fddf67318486d5facd938fb4bea77b43a563252a980e8826ce0794a806945f45e5b23a4d7650ca68585efbc68086b2c
I suppose the labels are incorrect. UF was 100, price rised to 115. Who pays whom the next day? Seller pays 15 into buyer's VM no? Then the label on the payment request is correct:
requests to pay into buyer VM
USD 15 due 2016-07-05
but the input box should change from
buyer pays sellecr VM
to seller pays buyer VM
_and_
the input moved to the seller's page?
Confirm pls.

**Comment by mcherifldn** [comment]
Correct on all.
